name: Build

on:
  push:
    branches:
      - "main"
      - "fix/**"
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.id }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: ubuntu-x86_64
            os: ubuntu-latest
            arch: x86_64
          - id: ubuntu-arm64
            os: ubuntu-24.04-arm
            arch: arm64
          - id: windows-x86_64
            os: windows-latest
            arch: x86_64
          - id: windows-arm64
            os: windows-11-arm
            arch: arm64
          - id: macos-x86_64
            os: macos-15-intel
            arch: x86_64
          - id: macos-26
            os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # install c compiler dependencies on linux
      - name: Install C compiler
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # setup ocaml
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.x'
          # set to false to prevent failing apt-get
          opam-depext: false
          # added: also disable depext tools to fully stop apt-get
          opam-depext-tools: false
          # added to help windows arm stability
          opam-disable-sandboxing: true
          
      # install dune/str via opam
      - name: Install Opam Dependencies
        run: opam install dune unix threads str --yes

      # build for (windows)
      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: dune build ./mp3packer.exe

      # build for (unix)
      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: dune build ./mp3packer

      # upload artifact (windows)
      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: mp3packer-${{ matrix.id }}
          path: _build/default/mp3packer.exe

      # upload artifact (unix - includes linux, macos)
      - name: Upload artifact (Unix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: mp3packer-${{ matrix.id }}
          path: _build/default/mp3packer

  build-freebsd:
    name: Build (freebsd-${{ matrix.arch }})
    runs-on: macos-14 # host runner for vmactions
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: freebsd-amd64
            arch: amd64
            freebsd-release: "14.3"
          - id: freebsd-arm64
            arch: arm64
            # changed: remove arch from release string
            freebsd-release: "14.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.freebsd-release }}
          # added: pass arch explicitly
          arch: ${{ matrix.arch }}
          usesh: true
          run: |
            # exit on error and print commands
            set -ex

            # 'str' is built-in to the ocaml compiler
            pkg install -y ocaml-findlib dune
            
            # setup opam
            opam init -a --compiler=ocaml-base-compiler.4.14.2
            eval $(opam env)
            
            # build for unix
            dune build ./mp3packer

      # upload artifact (unix - freebsd)
      - name: Upload artifact (Unix)
        uses: actions/upload-artifact@v4
        with:
          name: mp3packer-${{ matrix.id }}
          path: _build/default/mp3packer