name: OCaml CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build (${{ matrix.name }})
    
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ubuntu x64"
            os: ubuntu-22.04
            platform_id: ubuntu-x64
            ocaml-version: '4.14.2'
          - name: "Windows x64"
            os: windows-latest
            platform_id: windows-x64
            ocaml-version: '4.14.2'
          - name: "macOS ARM64"
            os: macos-26
            platform_id: macos-arm64
            ocaml-version: '4.14.2'
            
          - name: "Ubuntu ARM64"
            os: ubuntu-24.04-arm
            platform_id: ubuntu-arm64
            ocaml-version: '4.14.2'
            
          - name: "macOS x64"
            os: macos-15-intel
            platform_id: macos-x64
            ocaml-version: '4.14.2'

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3.4.5
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        dune-cache: true
      
    - name: Install dependencies and Build
      run: |
        opam install dune dune-configurator
        opam exec -- dune build
        
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: mp3packer-${{ matrix.platform_id }}
        path: _build/default/mp3packer.exe

  build-freebsd-x64:
    name: Build (FreeBSD x64)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Build on FreeBSD x64
        uses: vmactions/freebsd-vm@v1
        with:
          release: '15.0'
          arch: 'amd64'
          usesh: true
          prepare: |
            pkg install -y ocaml-opam ocaml-dune
          run: |
            opam init -a -y --disable-sandboxing
            opam switch create 4.14.2 -y
            eval $(opam env)
            
            opam install -y dune-configurator
            rm -rf ~/work/mp3packer/_build
            opam exec -- dune build --root ~/work/mp3packer mp3packer.exe
            
            cp ~/work/mp3packer/_build/default/mp3packer.exe ~/work/mp3packer-freebsd-x64
            
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: mp3packer-freebsd-x64
          path: mp3packer-freebsd-x64

  build-freebsd-arm64:
    name: Build (FreeBSD ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Build on FreeBSD ARM64
        uses: vmactions/freebsd-vm@v1
        with:
          release: '15.0'
          arch: 'arm64'
          usesh: true
          prepare: |
            pkg install -y ocaml-opam ocaml-dune
          run: |
            opam init -a -y --disable-sandboxing
            opam switch create 4.14.2 -y
            eval $(opam env)
            
            opam install -y dune-configurator
            rm -rf ~/work/mp3packer/_build
            opam exec -- dune build --root ~/work/mp3packer mp3packer.exe

            cp ~/work/mp3packer/_build/default/mp3packer.exe ~/work/mp3packer-freebsd-arm64
            
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: mp3packer-freebsd-arm64
          path: mp3packer-freebsd-arm64